
ALTER TABLE Customer
ADD FOREIGN KEY (address_id) REFERENCES Address(id)
ON UPDATE CASCADE
ON DELETE SET NULL;

ALTER TABLE "Order"
ADD FOREIGN KEY (status_id) REFERENCES OrderStatus(id)
ON UPDATE CASCADE
ON DELETE RESTRICT;

ALTER TABLE "Order"
ADD FOREIGN KEY (customer_id) REFERENCES Customer(id)
ON UPDATE CASCADE
ON DELETE SET NULL;

ALTER TABLE OrderItem
ADD FOREIGN KEY (order_id) REFERENCES "Order"(id)
ON UPDATE CASCADE
ON DELETE RESTRICT;

ALTER TABLE Product
ADD FOREIGN KEY (brand_id) REFERENCES Brand(id)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE OrderItem
ADD FOREIGN KEY (product_id) REFERENCES Product(id)
ON UPDATE CASCADE
ON DELETE RESTRICT;

ALTER TABLE CartItem
ADD FOREIGN KEY (product_id) REFERENCES Product(id)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE CartItem
ADD FOREIGN KEY (cart_id) REFERENCES Cart(id)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE Cart
ADD FOREIGN KEY (customer_id) REFERENCES Customer(id)
ON UPDATE CASCADE
ON DELETE CASCADE;

ALTER TABLE Customer
ADD FOREIGN KEY (cart_id) REFERENCES Cart(id)
ON UPDATE CASCADE
ON DELETE SET NULL;